application:
  enabled: true
  namespace: datastream
  name: datastream
  version: v1

controller:
  apiservice:
    host: 127.0.0.1
    port: 31900
    proxy:
      swagger:
        url: "/proxy/datastream/swagger/1"
      sqlite:
        url: "/proxy/datastream/sqlite/1"
        target:
          host: 127.0.0.1
          port: 18080
      grpc:
        url: "/proxy/datastream/grpc/1"
        target:
          host: 127.0.0.1
          port: 31200
      prometheus:
        url: "/proxy/datastream/prometheus"
        target:
          host: 127.0.0.1
          port: 9090
      grafana:
        url: "/proxy/datastream/grafana"
        target:
          host: 127.0.0.1
          port: 3000
      kafka:
        url: "/proxy/datastream/kafka"
        target:
          host: 127.0.0.1
          port: 8080
      repo:
        url: "/proxy/datastream/repo/public"
        target:
          host: 127.0.0.1
          port: 80
      cli:
        url: "/proxy/datastream/cli"
        target: 
          host: 127.0.0.1
          port: 55555
      kubernetesproxy:
        url: "/proxy/datastream/kubernetesproxy"
        target: 
          host: 127.0.0.1
          port: 44444
    ops:
      monitoring:
        api:
            url: "/ops/monitoring/api"

security:
  authentication:
    basic:
      admin:
        username: admin
        password: admin  
    