// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: service-cryptodatastream.proto

package v3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceCryptoDataStreamClient is the client API for ServiceCryptoDataStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceCryptoDataStreamClient interface {
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error)
	DeleteTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*Task, error)
	ReadTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Tasks, error)
}

type serviceCryptoDataStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCryptoDataStreamClient(cc grpc.ClientConnInterface) ServiceCryptoDataStreamClient {
	return &serviceCryptoDataStreamClient{cc}
}

func (c *serviceCryptoDataStreamClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/cryptodatastream.grpc.ServiceCryptoDataStream/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCryptoDataStreamClient) DeleteTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/cryptodatastream.grpc.ServiceCryptoDataStream/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCryptoDataStreamClient) ReadTask(ctx context.Context, in *String, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/cryptodatastream.grpc.ServiceCryptoDataStream/ReadTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCryptoDataStreamClient) ListTasks(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Tasks, error) {
	out := new(Tasks)
	err := c.cc.Invoke(ctx, "/cryptodatastream.grpc.ServiceCryptoDataStream/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceCryptoDataStreamServer is the server API for ServiceCryptoDataStream service.
// All implementations must embed UnimplementedServiceCryptoDataStreamServer
// for forward compatibility
type ServiceCryptoDataStreamServer interface {
	CreateTask(context.Context, *Task) (*Task, error)
	DeleteTask(context.Context, *String) (*Task, error)
	ReadTask(context.Context, *String) (*Task, error)
	ListTasks(context.Context, *Void) (*Tasks, error)
	mustEmbedUnimplementedServiceCryptoDataStreamServer()
}

// UnimplementedServiceCryptoDataStreamServer must be embedded to have forward compatible implementations.
type UnimplementedServiceCryptoDataStreamServer struct {
}

func (UnimplementedServiceCryptoDataStreamServer) CreateTask(context.Context, *Task) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedServiceCryptoDataStreamServer) DeleteTask(context.Context, *String) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedServiceCryptoDataStreamServer) ReadTask(context.Context, *String) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTask not implemented")
}
func (UnimplementedServiceCryptoDataStreamServer) ListTasks(context.Context, *Void) (*Tasks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedServiceCryptoDataStreamServer) mustEmbedUnimplementedServiceCryptoDataStreamServer() {
}

// UnsafeServiceCryptoDataStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCryptoDataStreamServer will
// result in compilation errors.
type UnsafeServiceCryptoDataStreamServer interface {
	mustEmbedUnimplementedServiceCryptoDataStreamServer()
}

func RegisterServiceCryptoDataStreamServer(s grpc.ServiceRegistrar, srv ServiceCryptoDataStreamServer) {
	s.RegisterService(&ServiceCryptoDataStream_ServiceDesc, srv)
}

func _ServiceCryptoDataStream_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCryptoDataStreamServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cryptodatastream.grpc.ServiceCryptoDataStream/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCryptoDataStreamServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCryptoDataStream_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCryptoDataStreamServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cryptodatastream.grpc.ServiceCryptoDataStream/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCryptoDataStreamServer).DeleteTask(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCryptoDataStream_ReadTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCryptoDataStreamServer).ReadTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cryptodatastream.grpc.ServiceCryptoDataStream/ReadTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCryptoDataStreamServer).ReadTask(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCryptoDataStream_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCryptoDataStreamServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cryptodatastream.grpc.ServiceCryptoDataStream/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCryptoDataStreamServer).ListTasks(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceCryptoDataStream_ServiceDesc is the grpc.ServiceDesc for ServiceCryptoDataStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCryptoDataStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptodatastream.grpc.ServiceCryptoDataStream",
	HandlerType: (*ServiceCryptoDataStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _ServiceCryptoDataStream_CreateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _ServiceCryptoDataStream_DeleteTask_Handler,
		},
		{
			MethodName: "ReadTask",
			Handler:    _ServiceCryptoDataStream_ReadTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ServiceCryptoDataStream_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service-cryptodatastream.proto",
}
